Project2: llvmast.LlvmPrimitiveType Class Reference
llvmast.LlvmPrimitiveType Class Reference
Public Member Functions
String toString ()
Static Public Attributes
static final LlvmType DOTDOTDOT = new LlvmPrimitiveType()
static final LlvmType I1 = new LlvmPrimitiveType()
static final LlvmType I32 = new LlvmPrimitiveType()
static final LlvmType I8 = new LlvmPrimitiveType()
static final LlvmType LABEL = new LlvmPrimitiveType()
static final LlvmType VOID = new LlvmPrimitiveType()
Member Function Documentation
String llvmast.LlvmPrimitiveType.toString ()
References llvmast.LlvmPrimitiveType.DOTDOTDOT, llvmast.LlvmPrimitiveType.I1, llvmast.LlvmPrimitiveType.I32, llvmast.LlvmPrimitiveType.I8, llvmast.LlvmPrimitiveType.LABEL, and llvmast.LlvmPrimitiveType.VOID.
{
     if(this == I1) return "i1";
     if(this == I8) return "i8";
     if(this == I32) return "i32";
     if(this == VOID) return "void";
     if(this == LABEL) return "label";
     if(this == DOTDOTDOT) return "...";
     return null;
     }
Member Data Documentation
final LlvmType llvmast.LlvmPrimitiveType.DOTDOTDOT = new LlvmPrimitiveType() static
Referenced by llvmast.LlvmPrimitiveType.toString().
final LlvmType llvmast.LlvmPrimitiveType.I1 = new LlvmPrimitiveType() static
Referenced by llvmast.LlvmBool.LlvmBool(), and llvmast.LlvmPrimitiveType.toString().
final LlvmType llvmast.LlvmPrimitiveType.I32 = new LlvmPrimitiveType() static
Referenced by llvmast.LlvmIntegerLiteral.LlvmIntegerLiteral(), llvmast.LlvmMalloc.MallocImpl(), and llvmast.LlvmPrimitiveType.toString().
final LlvmType llvmast.LlvmPrimitiveType.I8 = new LlvmPrimitiveType() static
Referenced by llvmast.LlvmMalloc.LlvmMalloc(), llvmast.LlvmMalloc.MallocImpl(), and llvmast.LlvmPrimitiveType.toString().
final LlvmType llvmast.LlvmPrimitiveType.LABEL = new LlvmPrimitiveType() static
Referenced by llvmast.LlvmLabelValue.LlvmLabelValue(), and llvmast.LlvmPrimitiveType.toString().
final LlvmType llvmast.LlvmPrimitiveType.VOID = new LlvmPrimitiveType() static
Referenced by llvmast.LlvmPrimitiveType.toString().
The documentation for this class was generated from the following file:
pacote/src/llvmast/LlvmPrimitiveType.java