Project2: llvm.SymTab Class Reference
llvm.SymTab Class Reference
Public Member Functions
SymTab ()
void add (String className, ClassData whichData)
LlvmValue FillTabSymbol (Program n)
ClassData getClassData (String whichClass)
int getClassSize (String whichClass)
String getOffset (String whichClass, String whichData)
void print ()
LlvmValue visit (Program n)
LlvmValue visit (MainClass n)
LlvmValue visit (ClassDeclSimple n)
LlvmValue visit (ClassDeclExtends n)
LlvmValue visit (VarDecl n)
LlvmValue visit (Formal n)
LlvmValue visit (MethodDecl n)
LlvmValue visit (IdentifierType n)
LlvmValue visit (IntArrayType n)
LlvmValue visit (BooleanType n)
LlvmValue visit (IntegerType n)
Public Attributes
ClassData classEnv
String className
MethodData methodEnv
Map< String, MethodData > methods
Package Attributes
String methodName
Private Attributes
Map< String, ClassData > classes
Constructor & Destructor Documentation
llvm.SymTab.SymTab ()
References llvm.SymTab.classes, and llvm.SymTab.methods.
     {
         this.classes = new HashMap<String, ClassData>();
         this.methods = new HashMap < String, MethodData > ();
     }
Member Function Documentation
void llvm.SymTab.add (String className, ClassData whichData)
References llvm.SymTab.classes.
Referenced by llvm.SymTab.visit().
     {
         this.classes.put( className, whichData );
     }
LlvmValue llvm.SymTab.FillTabSymbol (Program n)
Referenced by llvm.Codegen.translate().
{
         n.accept(this);
         return null;
     }
ClassData llvm.SymTab.getClassData (String whichClass)
References llvm.SymTab.classes.
Referenced by llvm.SymTab.getOffset(), and llvm.Codegen.visit().
     {
         return this.classes.get( whichClass );
     }
int llvm.SymTab.getClassSize (String whichClass)
References llvm.SymTab.classes.
Referenced by llvm.Codegen.visit().
     {
         ClassData aux = this.classes.get( whichClass );
         String parent = aux.getParent();
         if ( parent.isEmpty() )
             return aux.getSize();
         return aux.getSize() + getClassSize( parent );
     }
String llvm.SymTab.getOffset (String whichClass, String whichData)
References llvm.SymTab.getClassData().
     {
         ClassData aux = getClassData( whichClass );
         String offset = aux.getOffset( whichData );
         if ( offset.isEmpty() )
             return "0, " + getOffset( aux.getParent(), whichData );
         return offset;
     }
void llvm.SymTab.print ()
References llvm.SymTab.classes.
Referenced by llvm.Codegen.translate().
     {
         System.out.println( "\n====================================" );
         System.out.println( "Printing SymTab..." );
         System.out.println( "====================================" );
         for ( String key : this.classes.keySet() )
         {
             if ( key.isEmpty() ) break;
             System.out.println( "\n*************************" );
             System.out.println( "CLASS: " + key );
             System.out.println( "*************************" );
             System.out.println( "Size: " + Integer.toString( this.getClassSize( key ) ) );
             this.classes.get( key ).print();
         }
         System.out.println( "\n====================================\n" );
     }
LlvmValue llvm.SymTab.visit (Program n)
{
         System.out.println("[ SymTab ] : Program");
         n.mainClass.accept(this);
         for (util.List<ClassDecl> c = n.classList; c != null; c = c.tail)
             c.head.accept(this);
         return null;
     }
LlvmValue llvm.SymTab.visit (MainClass n)
{
         System.out.println("[ SymTab ] : MainClass");
         return null;
     }
LlvmValue llvm.SymTab.visit (ClassDeclSimple n)
References llvm.SymTab.add(), llvm.SymTab.classEnv, llvm.SymTab.className, llvm.SymTab.methodEnv, llvm.SymTab.methodName, and llvm.SymTab.methods.
{
         System.out.println("[ SymTab ] : ClassDeclSimple: " + n.name.toString() );
         // Starting a new class info. Here, we have no parent and offset is unnecessary
         classEnv = new ClassData();
         className = n.name.toString();
         int offset_aux = 0;
         ListConverter<VarDecl> converter0 = new ListConverter<VarDecl>();
         List<VarDecl> varList = converter0.getTList( n.varList );
         for ( VarDecl var : varList )
         {
             LlvmValue tmp = var.accept (this);
             // Adding a new attribute data
             AttributeData att_aux = new AttributeData( tmp.type, tmp, offset_aux );
             offset_aux++;
             classEnv.add( var.name.s, att_aux );
         }
         ListConverter<MethodDecl> converter1 = new ListConverter<MethodDecl>();
         List<MethodDecl> methodList = converter1.getTList( n.methodList );
         for ( MethodDecl method : methodList )
         {
             methodEnv = new MethodData ();
             method.accept(this);
             classEnv.add( methodName, methodEnv );
             methods.put ( methodName, methodEnv );
         }
         // Store this class
         this.add( className, classEnv );
         return null;
     }
LlvmValue llvm.SymTab.visit (ClassDeclExtends n)
References llvm.SymTab.add(), llvm.SymTab.classEnv, llvm.SymTab.className, llvm.SymTab.methodEnv, llvm.SymTab.methodName, and llvm.SymTab.methods.
{
         System.out.println("[ SymTab ] : ClassDeclExtends : " + n.name.toString() );
         ListConverter<VarDecl> util = new ListConverter<VarDecl>();
         List<VarDecl> varList = util.getTList( n.varList );
         // Starting a new class info. Here, we have no parent and offset is unnecessary
         String parent = n.superClass.toString();
         classEnv = new ClassData ( parent );
         className = n.name.toString();
         // != 0 -- Tem pai
         int offset_aux = 1;
         for ( VarDecl var : varList )
         {
             LlvmValue tmp = var.accept (this);
             // Adding a new attribute data
             AttributeData att_aux = new AttributeData( tmp.type, tmp, offset_aux );
             offset_aux++;
             classEnv.add( var.name.s, att_aux );
         }
         ListConverter<MethodDecl> converter0 = new ListConverter<MethodDecl>();
         List<MethodDecl> methodList = converter0.getTList( n.methodList );
         for ( MethodDecl method : methodList )
         {
             methodEnv = new MethodData ();
             method.accept(this);
             classEnv.add( methodName, methodEnv );
             methods.put ( methodName, methodEnv );
         }
         // Store this class
         this.add( className, classEnv );
         return null;
     }
LlvmValue llvm.SymTab.visit (VarDecl n)
{
         System.out.println("[ SymTab ] : VarDecl ");
         return n.type.accept(this);
     }
LlvmValue llvm.SymTab.visit (Formal n)
{
         System.out.println("[ SymTab ] : Formal ");
         LlvmRegister R1 = new LlvmRegister("%"+n.name.toString(), LlvmPrimitiveType.I32);
         return R1;
     }
LlvmValue llvm.SymTab.visit (MethodDecl n)
References llvm.SymTab.className, llvm.SymTab.methodEnv, and llvm.SymTab.methodName.
{
         System.out.println("[ SymTab ] : MethodDecl ");
         ListConverter<Formal> converter0 = new ListConverter<Formal>();
         List < Formal > FormalList = converter0.getTList ( n.formals );
         methodName = n.name.toString() + "_" + this.className;
         methodEnv.returnType = n.returnType.accept( this ).type;
         for ( Formal formal : FormalList )
         {
             LlvmValue formalAux = formal.accept(this);
             methodEnv.addArg ( formalAux.toString(), formalAux.type );
         }
         ListConverter<Statement> converter1 = new ListConverter<Statement>();
         List<Statement> bodyList = converter1.getTList( n.body );
         for ( Statement stmt : bodyList )
         {
             methodEnv.addStmt ( stmt );
         }
         methodEnv.returnExp = n.returnExp;
         ListConverter<VarDecl> converter2 = new ListConverter<VarDecl>();
         List<VarDecl> localList = converter2.getTList( n.locals );
         for ( VarDecl loc : localList )
         {
             LlvmValue aux = loc.accept( this );
             methodEnv.addLocal( loc.name.toString(), aux.type );
         }
         return null;
     }
LlvmValue llvm.SymTab.visit (IdentifierType n)
{
         System.out.println("[ SymTab ] : IdentifierType ");
         return new LlvmRegister ( n.name, new LlvmPointer ( new ClassType ( n.name ) ) );
     }
LlvmValue llvm.SymTab.visit (IntArrayType n)
{
         System.out.println("[ SymTab ] : IntArrayType ");
         return null;
     }
LlvmValue llvm.SymTab.visit (BooleanType n)
{
         System.out.println("[ SymTab ] : BooleanType ");
         return null;
     }
LlvmValue llvm.SymTab.visit (IntegerType n)
{
         System.out.println("[ SymTab ] : IntegerType ");
         return new LlvmIntegerLiteral (0);
     }
Member Data Documentation
ClassData llvm.SymTab.classEnv
Referenced by llvm.SymTab.visit().
Map<String, ClassData> llvm.SymTab.classes private
Referenced by llvm.SymTab.add(), llvm.SymTab.getClassData(), llvm.SymTab.getClassSize(), llvm.SymTab.print(), and llvm.SymTab.SymTab().
String llvm.SymTab.className
Referenced by llvm.Codegen.translate(), llvm.Codegen.visit(), and llvm.SymTab.visit().
MethodData llvm.SymTab.methodEnv
Referenced by llvm.Codegen.translate(), llvm.Codegen.visit(), and llvm.SymTab.visit().
String llvm.SymTab.methodName package
Referenced by llvm.Codegen.visit(), and llvm.SymTab.visit().
Map< String, MethodData > llvm.SymTab.methods
Referenced by llvm.SymTab.SymTab(), llvm.Codegen.translate(), and llvm.SymTab.visit().
The documentation for this class was generated from the following file:
pacote/src/llvm/Codegen.java